title: How to _______ Ubuntu
description: Ubuntu Tutorials and How to's
url: "https://howtoubuntu.org/" # the base hostname & protocol for your site

permalink: /:title/
page_excerpts: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
theme: jekyll-theme-cayman
