title: How to _______ Ubuntu
description: Ubuntu Tutorials and How to's
url: "https://lewisgoddard.github.io" # the base hostname & protocol for your site

permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed
theme: jekyll-theme-cayman
